### PR TITLE
added KL130

### PR DESCRIPTION
**Pull request by omarcostahamido**
I've added the control parameters I've tested so far.
This refers to #44

### CODE REVIEW

**Comment by konsumer** [comment]
Thanks for the testing and contribution!

**Comment by konsumer** [comment]
Did you test HSB? It seems to me that if it's a color bulb & HSB works, that hex should also work (it's derived from hsb)

**Comment by konsumer** [comment]
If it's not a color bulb, hsb should not work, but temp should.

**Comment by konsumer** [comment]
Of course, unless my hsb-to-hex code is broken...

**Comment by konsumer** [comment]
Oh, I bet this is misplaced `cloud` check-mark, and it's a non-color bulb, am-i-right? I will update matrix.

**Comment by ClaireSoftware** [comment]
Hey, I'm 99% sure the kl130 is a color bulb. I'm buying one of these on amazon to test. I'll report back in a few days :)

**Comment by konsumer** [comment]
Yep, [i'ts color](https://www.tp-link.com/uk/home-networking/smart-bulb/kl130/). We can update the table when you can test it.

**Pull request merged**
